{{- include "manager-chart-library.namespace" . }}
---
{{- include "manager-chart-library.operatorserviceaccount" . }}
---
{{- include "manager-chart-library.agentserviceaccount" . }}
---
{{- include "manager-chart-library.leaderelectionrole" . }}
---
{{- include "manager-chart-library.leaderelectionrolebinding" . }}
---
{{- include "manager-chart-library.daemonsetrole" . }}
---
{{- include "manager-chart-library.daemonsetrolebinding" . }}
---
{{- include "manager-chart-library.operatorclusterrole" . }}
---
{{- include "manager-chart-library.operatorclusterrolebinding" . }}
---
{{- include "manager-chart-library.agentclusterrole" . }}
---
{{- include "manager-chart-library.agentclusterrolebinding" . }}
---
{{- include "manager-chart-library.deployment" . }}
---
{{- include "manager-chart-library.powerconfig" . }}
